.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

Add strict enforcement since most of our commits already follows conventional commits.

chore: set up conventional commits enforcement

---

.prettierignore

fixes an error we get when we try to commit a new yarn version:
> 🔍  Finding changed files since git revision aac2d13.
> 🎯  Found 95 changed files.
>
> /workspaces/talisman-web/node_modules/prettier/index.js:13704
>     throw error.stack;
>     ^
> Error: prettier-plugin-import-sort:
> No configuration found for file type .cjs
> husky - pre-commit hook exited with code 1 (error)

fix: add .yarn and build to .prettierignore

---

.github/workflows/validation.yml

since we use a none default branch name `prod`

ci: add missing base branch

---

src/archetypes/Explore/hooks.tsx

- Set tags in one call to prevent multiple re-renders
- Move "Other" option to the end

fix: set tags

---

src/domains/nominationPools/hooks/useCountDownToNomsPool.ts

- push "go live" block for nomination pools back 600 blocks (enactment period)

fix: change nom pools available block

---

src/archetypes/NominationPools/AddStakeDialog.tsx

ESLint fix suggestion added `unbondExtrinsic.contents?.status.isInBlock`, since `contents` is possibly an error, and is typed as any. ESLint wasn't smart enough to detect that when suggesting the auto complete.

fix: null error

---

src/domains/accounts/recoils.ts
src/routes/Staking.tsx

For some of the items here, they will keep on spinning if the user hasn't connected an account, this PR will have them default to 0 instead:

refactor: selected accounts state & fallback

---

src/components/molecules/Select/Select.tsx

fix: collapsed select options doesn't hide completely when partially scrolled

---

apps/web/src/App.tsx

Needed since top navigation bar stick to top of view port now

style: add gap between toasts & top navigation bar

---

apps/web/src/domains/chains/recoils.ts
apps/web/src/domains/common/hooks/useExtrinsic.ts

Recoil selector call `Object.freeze` on returned value by default. This messed with `ApiPromise`. We can fix this by enabling `dangerouslyAllowMutability`.

fix: extrinsic dispatch error not being detected

---

apps/web/src/archetypes/NominationPools/Stakings.tsx
apps/web/src/components/atoms/Tooltip/Tooltip.tsx
apps/web/src/components/recipes/PoolStatusIndicator.tsx

- Tool tip was hidden on staking input
- On portfolio page, initial status was `not_earning_rewards`

fix: pool status indicator

---

apps/web/netlify.toml

The v0b indexer is currently offline (ran out of disk space - we're waiting on a request to add more), so we've spun up another one (v0a) which is only indexing the past month-ish of moonbeam.

fix: temporarily switched to v0a tx history indexer

---

apps/web/src/components/WalletNavConnector.tsx
apps/web/src/libs/talisman/useIsAnyWalletInstalled.ts

Fixed our Connect/Install button to allow user to connect with their existing wallet if they have one.
It was redirecting users to the talisman install page if it wasn't installed, preventing users to connect with polkadotjs or subwallet
It will now only redirect if there is no wallet installed, and show the existing wallet select modal otherwise
Note : this is a quick-fix solution, only 3 wallets are currently supported.

fix: allow pjs and subwallet users to connect even if Talisman is not installed

---

apps/web/src/archetypes/NominationPools/OwnPools.tsx
apps/web/src/archetypes/NominationPools/Stakings.tsx
apps/web/src/archetypes/NominationPools/Unstakings.tsx
apps/web/src/archetypes/NominationPools/ValidatorStakings.tsx
apps/web/src/archetypes/NominationPools/ValidatorUnstakings.tsx
apps/web/src/archetypes/Wallet/Crowdloans.tsx
apps/web/src/domains/accounts/recoils.ts
apps/web/src/domains/crowdloans/hooks.ts
apps/web/src/domains/fastUnstake/hooks.ts
apps/web/src/domains/nominationPools/hooks/usePoolUnlocking.ts
apps/web/src/domains/nominationPools/recoils.ts
apps/web/src/domains/staking/hooks/useTotalStaked.ts
apps/web/src/libs/crowdloans/useCrowdloanContributions.tsx
apps/web/src/routes/Staking.tsx

This is the correct term for substrate compatible accounts

chore: rename polkadot to substrate

---

apps/web/src/components/recipes/Asset/Asset.tsx
apps/web/src/components/recipes/AssetBreakdown/AssetBreakdownRow.tsx
apps/web/src/routes/AssetItem.tsx

Some asset logos were undefined and asset breakdown didn't show proper logos. Temporary fix for evm is the eth token from coingecko, but fix for substrate related tokens is taken from the github.

fix: fixed logos for assets in breakdown and undefined

---

apps/web/src/archetypes/NominationPools/PoolStakeItem.tsx
apps/web/src/components/recipes/ClaimStakeDialog/ClaimStakeDialog.stories.tsx
apps/web/src/components/recipes/ClaimStakeDialog/ClaimStakeDialog.tsx

The Figma design is wrong, as claim rewards doesn't occur in any lock duration.

fix: remove lock duration from claim rewards dialog

---

apps/web/src/archetypes/Portfolio/Assets.tsx
apps/web/src/components/recipes/Asset/Asset.tsx
apps/web/src/components/recipes/AssetBreakdown/AssetBreakdownRow.tsx
apps/web/src/index.tsx
apps/web/src/layout/Header.tsx
apps/web/src/routes/AssetItem.tsx
apps/web/src/routes/index.tsx

- Asset breakdowns's back button now takes you back to the page you came from using History.back()
- Removed a console.log

feat: Added navigation back from asset item using History

---

apps/web/package.json
apps/web/src/archetypes/Transaction/TransactionLogo.tsx
apps/web/src/domains/staking/recoils.ts
apps/web/src/domains/staking/worker.ts
apps/web/tsconfig.json
package.json
packages/development/tsconfig/react-library/tsconfig.json
packages/icons/package.json
packages/icons/src/index.ts
packages/icons/src/utils.ts
packages/icons/tsconfig.build.commonjs.json
packages/icons/tsconfig.build.json
packages/ui/package.json
packages/ui/src/atoms/Button/Button.tsx
packages/ui/src/atoms/Chip/Chip.tsx
packages/ui/src/atoms/Icon/Icon.stories.tsx
packages/ui/src/atoms/Text/Text.tsx
packages/ui/src/organisms/NavigationDrawer/NavigationDrawer.tsx
packages/ui/tsconfig.build.commonjs.json
packages/ui/tsconfig.build.json
yarn.lock

- Use new `bundler` module resolution strategy
- Only build ES modules for React library
- Use named export for icons lib utils

build: upgrade Typescript to v5

---

.vscode/settings.json
apps/web/src/components/recipes/PortfolioAllocationGraph/PortfolioAllocationGraph.tsx
apps/web/src/libs/@talisman-crowdloans/provider.ts
packages/ui/src/atoms/Text/Text.tsx
packages/ui/src/molecules/Details/Details.tsx

Fixes:
- serif font in UI when fonts still loading
- invalid baserow key crashing the UI
- vscode broken intellisense on unix due to strange `typescript.tsdk` path
now using the one recommended [in the vscode docs](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript) instead

Fix: (serif font) && (baserow crash) && (typescript sdk path)

---

apps/web/src/libs/@talisman-crowdloans/provider.ts
apps/web/src/routes/Crowdloan.Detail.tsx

This allows us to set whether or not a crowdloan can be contributed to by changing the toggle on baserow. Helps prevent unnecessary contributions to self funded crowdloans.

feat: ability to set crowdloan contrib through baserow. 

---

.husky/pre-commit

failure does not produce correct exit code when running in parallel

build: fix pre-commit script

---

packages/ui/src/atoms/FloatingPortal.tsx

should check for dialog regardless of status
because we are running a `contains` check anyway

fix: floating portal

---

apps/web/src/components/recipes/ExportTxHistoryDialog/ExportTxHistoryDialog.tsx
apps/web/src/components/recipes/StakeForm/StakeForm.stories.tsx
apps/web/src/components/recipes/TeleportForm/TeleportForm.stories.tsx
apps/web/src/components/recipes/TeleportForm/TeleportForm.tsx
apps/web/src/components/widgets/AccountSelector.tsx
apps/web/src/components/widgets/staking/StakeForm.tsx
packages/ui/src/molecules/Select/Select.stories.tsx
packages/ui/src/molecules/Select/Select.tsx

- value can only be `undefined` when select can clear value
- rename `Item` to `Option` to match native HTML element

refactor: `Select` component

---

apps/web/src/domains/nfts/recoils.ts

Using `from` on `thread.js` observable causes unexpected behaviour of not all events coming through. Possibly a compile issue. Needs to investigate further.

fix: observable interop

---

packages/nft/src/generators/orml/index.ts

- Acala documentation has Dwellir as the first option
- We no longer have to refrain from using WS connection after the balances lib improvement

chore: update nfts rpc endpoints

---

apps/web/src/domains/nominationPools/hooks/usePoolStake.ts

User shouldn't be able to receive any reward when their active balance is 0

fix: reward status when user fully unstake

---

apps/web/src/routes/Collectibles.tsx

Show loader for individual accounts. Instead of one for all account.
This will allow faster loaded account to show up first regardless of others.

perf: nfts loading

---

apps/web/package.json
apps/web/src/components/recipes/StakeForm/StakeForm.tsx
apps/web/src/components/recipes/StakeItem/StakeItem.tsx
apps/web/src/components/recipes/TransportForm/Transport.tsx
packages/ui/package.json
packages/ui/src/atoms/FloatingActionButton/FloatingActionButton.tsx
packages/ui/src/atoms/IconButton/IconButton.tsx
packages/ui/src/atoms/Identicon/Identicon.tsx
packages/ui/src/atoms/Text/Text.tsx
packages/ui/src/organisms/NavigationDrawer/NavigationDrawer.tsx
yarn.lock

For the "Orb" component that can't be migrated. Only import needed functions for tree-shaking.

refactor: use new native CSS `color-mix` functionality

---

packages/ui/src/atoms/Button/Button.tsx

Text component was overriding button text colour on hover

fix: button hover text color

---

.github/workflows/deploy.yml

This reverts commit 1ea4647757f75ea36163bc1336c26ec024aa7fdb.
We're still seeing incorrect branch name on Cloudflare Pages with this version

chore: revert "ci: bump cf pages action"

---

apps/web/src/components/widgets/staking/ValidatorStakeItem.tsx
apps/web/src/components/widgets/staking/ValidatorStakes.tsx

Azero doesn't implement fast unstake, hence we can't read fast unstake deposit
Fixes #704

fix: azero fast unstake error

---

apps/web/src/components/widgets/ErrorBoundary.tsx
apps/web/src/components/widgets/staking/PoolStakes.tsx
apps/web/src/components/widgets/staking/Stakes.tsx
apps/web/src/components/widgets/staking/ValidatorStakes.tsx

Let other stake positions display as normal event if some positions had errors

refactor: more granular error boundaries

---

apps/web/src/domains/nfts/core.ts

When there's no NFT, we only need to set the initially resolved value
Fix #715

fix: using an updater function while the current state is pending

---

apps/multisig/src/domains/metadata-service/getTxMetadata.tsx
apps/multisig/src/domains/multisig/index.ts
apps/multisig/src/domains/tx-history/index.tsx
apps/multisig/src/layouts/Overview/Transactions/index.tsx

This PR updates Transactions to use their Multisig ID, which is constructed from [Timepoint](https://paritytech.github.io/substrate/master/pallet_multisig/struct.Timepoint.html), instead of call hash as unique identifier. Call hashes aren't necessarily unique because transactions that do the exact same thing will have the same hash value.
Before:
After:

fix: use multisig id as identifier

---

apps/multisig/src/graphql/fetch-graphql.ts

Move the error toast to console.error for now since it's just a spam of `tx-history 500 error` to the frontend atm with no actual benefit to the UX

fix(signet): move tx-history 500 error to console

---

apps/multisig/src/layouts/CreateMultisig/VaultCreated.tsx
apps/multisig/src/layouts/Overview/NewTransactionModal/MultiSendAction.tsx

This PR addresses UI anomaly on two screens:

fix: only show scrollbar when need to

---

apps/multisig/src/domains/balances/index.ts
apps/multisig/src/domains/chains/extrinsics.ts
apps/multisig/src/domains/multisig/index.ts
apps/multisig/src/domains/tx-history/index.tsx
apps/multisig/src/layouts/Overview/Assets.tsx
apps/multisig/src/util/misc.ts

This PR addresses 2 issues:
1. Transaction ID should included chain-id to avoid having transactions with same id across different chains
2. ID of each TokenRow under Assets should use a string that is a combination of token id + account address to avoid the error below where the same asset is rendered multiple times when you switch between single / multiple multisig view. The issue is because non-unique asset ID is passed to array mapping and React cant handle that properly:
Fixed:
https://github.com/TalismanSociety/talisman-web/assets/81092286/4fc759c4-ab45-45db-8282-8ff3f61f838d

fix(signet): transaction id and asset id

---

apps/web/src/domains/chains/config.ts

- update preferred nomination pool for Polkadot to #16, ahead of the #greatunlock

chore: update preferred pool

---

apps/multisig/src/components/AccountSwitcher.tsx
apps/multisig/src/components/AddressInput/NameAndAddress.tsx
apps/multisig/src/components/AddressPill/index.tsx
apps/multisig/src/components/Member.tsx
apps/multisig/src/components/MemberRow/index.tsx
apps/multisig/src/components/MultisigSelect.tsx
apps/multisig/src/layouts/AddressBook/index.tsx
apps/multisig/src/layouts/Auth/AccountComboBox.tsx
apps/multisig/src/layouts/Overview/NewTransactionModal/multisend/MultiLineSendInput.tsx
apps/multisig/src/util/addresses.ts

This PR creates a `shortenAddress` util function that consistently truncate addresses across the app. It also adds a toShortSs58 to the `Address` class for ease of use.

refactor: consistent addresses length

---

apps/web/src/domains/bridge/index.ts

Disable Kusama XCM routes, due to an issue with Kusama XCM teleports and RATs. Example:
https://kusama.subscan.io/xcm_message/kusama-98082ccbd5ae3e416b17276a0aaaeadd85aecb7a

fix: temporarily remove kusama XCM routes

---

apps/web/src/domains/extension/wagmi.tsx

after a long period of usage wagmi hooks start throwing error that will only went away after deleting `wagmi.cache` from `localStorage`

fix: corrupted Wagmi cache

---

packages/ui/src/molecules/MediaDialog/MediaDialog.tsx

Block display for some reason has children not stretching to the last ~3 pixels:

style: fix media dialog media not filling the container completely

---

apps/web/src/components/widgets/AccountsManagementMenu.tsx

simply setting selected account addresses to `undefined` won't trigger the effect to clear lookup account, if the value is already `undefined`, since `undefined` in dependencies doesn't re-trigger effect hook

fix: lookup account doesn't clear after selecting all accounts

---

apps/web/src/components/recipes/AccountValueInfo/AccountValueInfo.tsx
apps/web/src/components/widgets/AccountsManagementMenu.tsx

reduce confusion as the default selection doesn't include readonly accounts that are not part of portfolio

chore: change "All accounts" to "My accounts"

---

apps/web/src/domains/common/hooks/useExtrinsic.ts
apps/web/src/domains/common/hooks/useExtrinsicBatch.ts

```ts
const extrinsic = useExtrinsic(
useCallback(
(api: ApiPromise) => api.tx.utility.batchAll([api.tx.remark.store('foo'), api.tx.remark.store('bar')]),
[]
)
)
```

refactor: allow passing of tx builder function to `useExtrinsic` hook

---

apps/web/src/domains/extension/wagmi.tsx

some weird issue with storage corruption
could re-enable storage again after migrating to Wagmi V2

fix: use Wagmi NOOP storage

---

apps/web/src/components/widgets/staking/dappStaking/StakeSideSheet.tsx
apps/web/src/components/widgets/staking/dappStaking/Stakes.tsx

When opening stake side sheet from locked token dialog, stake side sheet should pre-populate account selection with the selected account

feat: use selected account when re-staking

---

packages/ui/README.md
packages/ui/src/global.d.ts
packages/ui/src/theme.tsx

So that consumer of the package don't have to augment theme type manually

refactor: export theme module declaration

---

apps/web/src/components/widgets/dex/TransportForm.tsx
apps/web/src/domains/bridge/index.ts
packages/ui/src/atoms/IconButton/IconButton.tsx
packages/ui/src/molecules/TextInput/TextInput.tsx

https://github.com/paritytech/polkadot-sdk/issues/3050#issuecomment-1971375971

chore: disable Polkadot Asset Hub due to potential issue of losing fund

---

apps/web/src/domains/balances/core.ts
apps/web/src/domains/chains/recoils.ts

We no longer need to do this with the Coingecko proxy, plus performance is much better when not using balances library since multiple components won't have to re-render any more every time balances library update itself.

chore: revert "perf: fetch token rates from balances lib"

---

apps/web/src/domains/common/recoils/api.ts

- Seems a lot less prone to hiccup for some reason
- Downside is there's no clean-up function, but we don't do this for API state currently, so there's no real world different

perf: use selector family for API state

---

apps/web/src/domains/common/consts.ts
apps/web/src/domains/common/errors.ts
apps/web/src/domains/common/hooks/useExtrinsic.ts
apps/web/src/domains/common/sentry.ts

refactor: use custom error class instead of symbol to skip error reporting

---

apps/web/src/domains/bridge/index.ts

Due to reports of possible lost of funds from users

chore: disable routes from asset hub

---

apps/web/src/domains/staking/substrate/nominationPools/recoils.ts

Using this free tier key is the same as providing no key

chore: remove Subscan API key

---

packages/ui/src/molecules/TextInput/TextInput.tsx

Empty character is not rendered when label or supporting text contains wrapper elements

style: fix text input supporting text spacing

---

apps/portal/src/components/widgets/staking/dappStaking/Stakes.tsx
apps/portal/src/domains/staking/dappStaking/hooks/useClaimAllRewardsExtrinsic.ts
apps/portal/src/domains/staking/dappStaking/hooks/useStakeLoadable.ts
packages/ui-recipes/src/StakePosition/StakePosition.tsx

This PR fixes the following issues:
1. Hide ellipsis menu when no operation is available
2. Attention required red dot being displayed on ellipsis menu top right when it should not be displayed
3. Not earning rewards message when tokens are actually staked and earning rewards
4. Unable to claim staking rewards
Was not able to reproduce item 3, may still exist. I suspect it could be a stale value, memoized `earningRewards` value calculation to mitigate the issue.

[FIX] - Astar Staking issues

---

apps/portal/src/components/recipes/TokenSelectDialog.tsx
apps/portal/src/components/widgets/chainflip-swap/FromAmount.tsx
apps/portal/src/components/widgets/chainflip-swap/index.tsx
apps/portal/src/components/widgets/chainflip-swap/swap-modules/chainflip.swap-module.ts
apps/portal/src/components/widgets/chainflip-swap/swap-modules/common.swap-module.ts
apps/portal/src/components/widgets/chainflip-swap/swaps.api.ts
apps/portal/src/hooks/useFastBalance.ts
apps/portal/src/hooks/useSubstrateBalance.ts
packages/ui/package.json

- swap amount subtracts gas buffer when swapping from native token
- allow transferAllowDeath

feat: improved swap amount

---

apps/portal/src/domains/nfts/worker.ts

We would like to turn off RMRK 2 indexer for some period of time (update / maintenance)
and we would like to not to break talisman wallet ^-^ 
remove import of `createRmrk2NftAsyncGenerator`.

:technologist: hide RMRK2 NFTs

---

apps/portal/src/domains/staking/subtensor/atoms/taostats.ts
apps/portal/src/domains/staking/subtensor/hooks/useApr.ts

Taostats api has changed and the endpoint we used has been depricated. Unfortunately the new API does not expose any endpoint that contains  `staking_apy` data and, so we will default APY to '--' in the meantime.
They will provide an API within this week or next according to [this conversation](https://discord.com/channels/1214123725788553266/1214124201712025671/1285179933940912188) in their [Discord channel](https://discord.gg/hSG3dmGr), then we need to update

fix: default TAO apy to "--" when API fails

---

apps/portal/src/domains/bridge/index.ts

Re-enabling Kusama XCM routes, since the problem was solved according to the issue on the comments.
I suppose there is also a way to recover trapped assets by now.

chore: re-enable-ksm-routes

---

apps/portal/src/routes/portfolio/collectibles.tsx

Check if NFT belongs to "OG WUD BURN" collection and user kodadot ipfs gateway.

fix: use kokodot ipfs gateway for Og wud burn collection

---

apps/portal/src/components/recipes/StakePosition/StakePosition.tsx
apps/portal/src/components/recipes/StakeProvider/StakeProvider.tsx

Fixed:
- Network icons being clipped on the top on Stake Providers and Stake positions page
- Network icons being positioned far to the right on on Portfolio page and smaller screens

fix: network icons clipping

---

apps/portal/src/routes/portfolio/collectibles.tsx

Closed original PR https://github.com/TalismanSociety/talisman-web/pull/1192 from @vikiival due to CI & CD issues for branches created from non-organisation members. An issue has been created to address this problem https://github.com/TalismanSociety/talisman-web/issues/1193
Thanks @vikiival!
Reverts TalismanSociety/talisman-web#1190 and TalismanSociety/talisman-web#1191
Hey, we have found a root caused that caused this hiccup
as a responsible OSS we will publish a post-mortem.
I am proposing to revert this PR as it was issue from our side and you do not need to have mess in your code. 
I already checked your gw - it is returning the images
[image](https://talisman.mypinata.cloud/ipfs/QmYUhpc4MHY8uZQiYLD7TBqLnqfKYFeuTgfzz9paAYsyVG)

revert: "use kodadot ipfs gateway for Og wud burn collection"

---

apps/portal/src/components/widgets/staking/slpx/UnlockDuration.tsx
apps/portal/src/components/widgets/staking/slpxSubstrate/UnlockDuration.tsx

Updated Bifrost's providers unbonding period to include "0" to X days, as there is not fixed term.

chore: updated Bifrost unbonding period copy

---

apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx
apps/portal/src/domains/staking/subtensor/atoms/taostats.ts
apps/portal/src/domains/staking/subtensor/hooks/useApr.ts
apps/portal/src/domains/staking/subtensor/types.ts

Updated Taostats api calls and response parsing to match upcoming changes. See [docs](https://docs.taostats.io/reference/get-validator).
Update the API URL between November 1st and **_before_** December 1st. Check [import API Updates](https://docs.taostats.io/reference/important-api-updates) for more details
Please delete options that are not relevant.
- Visit `/staking/providers`
Expected: Est. return should be displayed
- Click on "stake" on TAO row
Expected: Total Staked should display selected currency amount, or TAO amount when currency price is not available. Estimated APR should be displayed
- Click on Select Delegate
Expected: Estimated APR should be displayed and sorting by Estimated APR should work 
https://github.com/user-attachments/assets/955e3cea-b574-4195-9e3d-71f7a411b7d3

refactor: updated Taostats api call endpoints

---

apps/portal/src/components/widgets/staking/substrate/ValidatorStakeItem.tsx
apps/portal/src/domains/staking/substrate/validator/hooks/useTotalRewards.ts

- Refactor useTotalRewards hook to return error if api call fails
- Refactor UI to display "--" in Total rewards table cell when data is unavailable

refactor: display "--" as placeholder when total rewards api call fails

---

apps/portal/src/components/legacy/archetypes/Portfolio/Assets.tsx
apps/portal/src/components/recipes/Asset/Asset.tsx
apps/portal/src/components/recipes/AssetBreakdown/AssetBreakdownList.tsx
apps/portal/src/components/recipes/AssetBreakdown/AssetBreakdownRow.tsx
apps/portal/src/routes/portfolio/assets/item.tsx

Fixes:
- Don't add border-radius to chaindata icons
- Don't show chain name/id where only token is shown (and thus many chains are relevant)
- Alert triangle should be inline with balance

fix: some portfolio icon bugs

---

apps/portal/src/components/recipes/AddStakeDialog/AddStakeDialog.tsx
apps/portal/src/components/recipes/UnstakeDialog/UnstakeDialog.tsx
apps/portal/src/components/widgets/staking/slpx/StakeSideSheet.tsx
apps/portal/src/components/widgets/staking/slpxSubstrate/AddStakeSideSheet.tsx
apps/portal/src/domains/staking/slpx/core.ts

- fix: do not throw if no eth account is connected
- close side sheet on tx success
- updated approve copy to Approve Spend
https://github.com/user-attachments/assets/bc43981a-36ac-4a46-9496-3e6c6c0c6c24

refactor: close side sheet on tx success - Slpx

---

apps/portal/src/components/widgets/staking/providers/components/StakeProvidersTable.tsx
apps/portal/src/components/widgets/staking/providers/hooks/types.ts
apps/portal/src/domains/staking/utils/getPosition.ts

- Default order Stake providers by curated position
- Reposition TAO as 2nd provider of the list

feat: Display staking providers by position

---

apps/portal/src/hooks/useFastBalance.ts

Switched from wagmi to viem for useFastBalance, so that if the balance is able to load in the token picker, there's a better chance it will also load after the token has been selected.

fix: balance never loads in swaps for `S` on sonic

---

apps/portal/src/components/widgets/staking/subtensor/constants.ts
apps/portal/src/domains/staking/subtensor/atoms/accountStake.ts
apps/portal/src/domains/staking/subtensor/hooks/forms.ts

Support root net id for subnet staking.
Since changes are not in prod, a try catch block has been added to handle 'default' staking and the new subnet staking on root net with `netuid = 0`
Could't find any docs on it, but FAFOing around I noticed the `getStakeInfoForColdkey` now expects an address str as arg when before it expected a address vector.
For anyone interested in checking themselves:
- Go to polkadot js on [bittensor testnet runtime calls](https://polkadot.js.org/apps/?rpc=wss://test.chain.opentensor.ai:443#/runtime)
- Select `stakeInfoRuntimeApi` and `getStakeInfoForColdkey`
Note:
For reasons beyond my comprehension, it was simply not possible to call the exact same methods without vectorizing the address. It will throw.
Eg:
```const response = (await …
```

feat: support rootnet subnet staking

---

apps/portal/src/domains/staking/subtensor/hooks/useCombineSubnetData.ts
apps/portal/src/domains/staking/subtensor/hooks/useCombinedBittensorValidatorsData.ts

Store combined api response data in state, do not update state if api call fails.
The API calls are being pre populated with placeholder data, which then gets hydrated with fresh data from api responses. The issue arises when the api response fail, and placeholder data then gets replaced by `null`

feat: store combined data in state, return if api call fails

---

apps/portal/src/components/widgets/staking/subtensor/Stakes.tsx

Fixes increase stake modal being opening after extrinsic has been successfully included in the block by clicking on "change validator"
- `useExtrinsicInBlockOrErrorEffect` hook is alive in memory somewhere, and passing a function that toggles state will keep toggling it. The quick and easy solution is to pass a callback fn that set state to false.

fix: Add stake modal toggling open when changing validator

---

apps/portal/src/components/widgets/staking/subtensor/StakeItemRow.tsx

Defaults to "Managed delegation" label when not staked with any known subnets known to taostats api
Add the following watched account, it should display "Managed delegation" for their Mentat minds staked positions: 5Co21odW75rPN1btp9FEPEnPd4t7WJoSCUcsyvTbHVVnLAHp

chore: default provider name to manage delegation

---

apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx
apps/portal/src/components/widgets/staking/subtensor/StakeForm.tsx
apps/portal/src/domains/staking/subtensor/hooks/useApr.ts
apps/portal/src/domains/staking/subtensor/hooks/useCombinedBittensorValidatorsData.ts
apps/portal/src/domains/staking/subtensor/hooks/useGetBittensorInfiniteValidators.ts
apps/portal/src/domains/staking/subtensor/types.ts

Updated taostats api endpoint on `useGetBittensorInfiniteValidators` hook. This new endpoint does not offer APR (for now) so any code displaying/sorting APRs has temporarily commented out and APR is being displayed as "--"

chore: updated toastats api endpoints

---

apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx

Updated bittensor yield copy to APY

chore: updated bitensor APY copy

---

apps/portal/src/components/widgets/staking/subtensor/SubnetSelectorCard.tsx
apps/portal/src/components/widgets/staking/subtensor/SubnetSelectorDialog.tsx

- Change subnet select modal default sort order to Total Alpha
- Fix Token units wrapping into two lines, display "29k TAO" instead of "29,000.00 TAO"

chore: change default sort order

---

apps/portal/.env.example
apps/portal/src/components/widgets/swap/swap-modules/chainflip.swap-module.ts
apps/portal/src/vite-env.d.ts

* Added the Talisman **Public** API key, this can be exposed.
* Switched to use it for mainnet, testnet is just the common testnet key.
* Removed `boostFeeBps` on quote, this does not exist
Remaining TODO's to make the integration work again:
* `fillOrKillParams` is now a required field.

feat: switch to broker as a service for CF

---

apps/portal/src/components/widgets/staking/providers/hooks/nominationPools/useNominationPoolsProviders.ts

- Filter out Cere from providers to prevent more users from staking while we wait on unstaking fixes.
- Cere still listed on Staking positions page.
https://github.com/user-attachments/assets/b629d3f8-a23d-490d-bc05-e65ccedff41c

chore: filter Cere out from providers

---

apps/portal/src/components/widgets/staking/subtensor/StakeItemRow.tsx

Removes "Managed delegation" copy, and displays stake hotkey instead. This helps displaying the correct status and hotkey for dTao miners.

feat: remove managed staking, display stake hotkey and tooltip
