public/locales/cn/banners.json, public/locales/cn/connect-wallet.json, public/locales/cn/crowdloan.json, public/locales/cn/errors.json, public/locales/cn/filters.json, public/locales/cn/translation.json, public/locales/cn/welcome.json
Some slight adjustments to Chinese text
=> Chinese Adjustments

src/libs/talisman/crowdloan.tsx
To be merged on [2021-11-22 at 15:00 UTC](https://time.is/1500_22_Nov_2021_in_UTC)
=> added capped status override to moonbeam crowdloan

public/locales/ptbr/banners.json, public/locales/ptbr/connect-wallet.json, public/locales/ptbr/crowdloan-details.json, public/locales/ptbr/crowdloan.json, public/locales/ptbr/errors.json, public/locales/ptbr/filters.json, public/locales/ptbr/languages.json, public/locales/ptbr/nav.json, public/locales/ptbr/parachain-details.json, public/locales/ptbr/translation.json, public/locales/ptbr/welcome.json
Translations to portuguese for Talisman by Junqueira
=> Translations to portuguese for Talisman by Junqueira

src/libs/talisman/util/_config.ts
- add zeitgeist crowdloan details to _config.ts
=> add zeitgeist crowdloan

src/archetypes/Crowdloan/Contribute.tsx, src/libs/crowdloans/crowdloanOverrides.ts, src/libs/crowdloans/useCrowdloanContribute.tsx
- building the zeitgeit contribution tx (appending an extra remark to acknowledge terms)
- added note on modal to display terms
=> Zeitgeist terms

public/locales/fr/spirit-keys.json
Localization of spirit-keys.json
=> i18n - FR - Update spirit-keys.json

public/locales/cn/spirit-keys.json, public/locales/de/spirit-keys.json, public/locales/en/spirit-keys.json, public/locales/es/spirit-keys.json, public/locales/fr/spirit-keys.json, public/locales/ptbr/spirit-keys.json, public/locales/ru/spirit-keys.json, public/locales/th/spirit-keys.json, src/libs/spiritkey/HowToGetInfo.tsx, src/routes/SpiritKeysPage.tsx
- Updated text from 'benefits' to 'Where can I get one?' for spirit key page.
- Bonus spanish translation
TODO: Chinese translation
=> Updated text from 'benefits' to 'Where can I get one?' 

src/libs/talisman/util/_config.ts
- Append the crowdloan details to the config.
=> Add Litmus and Sora Kusama crowdloans

src/libs/talisman/util/_config.ts
- add kico crowdloan details in config
=> add kico crowdloan

src/libs/tokenprices/index.tsx
- filter for incorrect asset (paralink-network) in `_useTokenPrices` hook
=> Patch para price

src/libs/talisman/extension.tsx
=> Fix bug: Amounts do not clear when Accounts gets disconnected

src/components/Field.tsx, src/components/Menu.tsx
Before
After
Fixed the chevron spacing and background colour on hover.
=> fix: minor changes to the language selector and mischelleneous bars

package.json, src/components/molecules/Select/Select.stories.tsx, src/components/molecules/Select/Select.tsx, src/components/recipes/StakingInput/StakingInput.tsx, src/util/monads.ts, yarn.lock
- fix overflow
- refactor props to match standard HTML select element
Demo: https://deploy-preview-365--talisman-storybook.netlify.app/?path=/story/molecules-select--overflow
=> refactor: select component

apps/web/src/App.tsx, apps/web/src/archetypes/DevMenu.tsx, apps/web/src/libs/portfolio/index.tsx, apps/web/src/libs/tokenprices/index.tsx, apps/web/src/routes/index.tsx
`react-router` routers: https://reactrouter.com/en/main/routers/picking-a-router
Type errors: #340
=> refactor: data APIs compatible router & type errors

LICENSE, README.md, apps/web/LICENSE, apps/web/package.json, package.json
=> chore: add license & update `package.json` files

apps/web/package.json, apps/web/src/layout/Header.js, yarn.lock
- Frosted backdrop effect when scrolled down
- Active navigation link animation
=> style: improve top navigation bar

apps/web/package.json, yarn.lock
Fixed issue with fee calculation on Westend
https://github.com/paritytech/polkadot-staking-dashboard/pull/348
=> build: bump polkadot.js

apps/web/src/components/molecules/AlertDialog/AlertDialog.tsx, apps/web/src/components/recipes/AddStakeDialog/AddStakeDialog.tsx, apps/web/src/components/recipes/PoolSelectorDialog/PoolSelectorDialog.stories.tsx, apps/web/src/components/recipes/PoolSelectorDialog/PoolSelectorDialog.tsx, apps/web/src/components/recipes/PoolSelectorItem/PoolSelectorItem.stories.tsx, apps/web/src/components/recipes/UnstakeAlertDialog/UnstakeAlertDialog.tsx, apps/web/src/components/recipes/UnstakeDialog/UnstakeDialog.tsx
- Disable body scroll when dialog is open
- Prevent dialog from being too small by setting explicit width
=> style: dialog

apps/web/src/App.tsx, apps/web/src/routes/index.tsx
- Legacy modal render outside of RouterProvider
- This caused crash on mobile where the desktop required modal is displayed
=> fix: legacy modal

apps/web/src/archetypes/NFT/Modal/NftDialog.tsx
Attributes on some NFTs have objects as their values, this temporary fix checks if the value is a string. If it isn't return `unknown`.
No NFT standards in the dotworld 😢
=> fix: fixed issues with nfts attributes trying to access objects within objects

apps/web/netlify.toml
This reverts commit d30b2214cfa01c52cb0c89b68d276c8641bd9c84.
=> fix: switched back to v0b tx history indexer

apps/web/src/archetypes/NominationPools/ValidatorStakeItem.tsx
Cases where controller account is different from stash account
=> fix: traditional staking available to unstake amount

apps/web/src/archetypes/CookieBanner.tsx
- increase `zIndex` on cookie banner.
=> fix: z-index on cookie banner

apps/web/src/libs/talisman/util/_config.ts
- add bittensor crowdloan to config
=> feat: bittensor crowdloan

apps/web/src/archetypes/NominationPools/AddStakeDialog.tsx, apps/web/src/archetypes/NominationPools/PoolStakeItem.tsx, apps/web/src/archetypes/NominationPools/UnstakeDialog.tsx, apps/web/src/archetypes/NominationPools/Unstakings.tsx, apps/web/src/archetypes/NominationPools/ValidatorStakeItem.tsx, apps/web/src/archetypes/NominationPools/ValidatorUnstakeDialog.tsx, apps/web/src/archetypes/NominationPools/ValidatorUnstakings.tsx, apps/web/src/domains/chains/recoils.ts, apps/web/src/domains/common/hooks/useTokenAmount.ts, apps/web/src/domains/nominationPools/hooks/usePoolAddForm.ts, apps/web/src/domains/nominationPools/hooks/usePoolUnstakeForm.ts, apps/web/src/domains/staking/hooks/useTotalStaked.ts, apps/web/src/domains/staking/hooks/useValidatorUnstakeForm.ts, apps/web/src/routes/Staking.tsx, apps/web/src/util/Decimal.ts
To adhere to substrate convention
=> chore: rename `atomics` to `planck`

apps/web/src/archetypes/Portfolio/Assets.tsx, apps/web/src/components/recipes/Asset/Asset.tsx, apps/web/src/components/recipes/AssetBreakdown/AssetBreakdownRow.tsx, apps/web/src/index.tsx, apps/web/src/layout/Header.tsx, apps/web/src/routes/Overview.tsx, apps/web/src/routes/index.tsx
hide 'not installed' wallets from the wallet select
=> fix: hide not installed wallets

apps/web/src/archetypes/Portfolio/Assets.tsx, apps/web/src/archetypes/Wallet/Total.tsx, apps/web/src/components/molecules/AccountValueInfo/AccountValueInfo.tsx, apps/web/src/libs/talisman/balances.tsx, apps/web/src/routes/Assets.tsx, apps/web/src/routes/Portfolio.tsx
Provider was using a suspendable hook which is an anti-pattern
=> perf: uncaught suspense

apps/web/src/App.tsx, apps/web/src/archetypes/DevMenu.tsx, apps/web/src/archetypes/Development/DevMenu.tsx, apps/web/src/archetypes/Development/Development.tsx, apps/web/src/archetypes/Development/index.ts
- Fix dev menu styling & layout
- Implement code splitting to only serve development bundle on request (save on production bundle size)
=> chore: improve development menu

apps/web/src/domains/chains/config.ts, apps/web/src/domains/chains/recoils.ts, apps/web/src/domains/common/utils/toast.tsx
=> refactor: remove chaindata squid dependency from staking

apps/web/.env.example, apps/web/package.json, apps/web/src/index.tsx, apps/web/src/react-app-env.d.ts, apps/web/src/routes/index.tsx, yarn.lock
=> feat: error reporting

apps/web/src/domains/nominationPools/recoils.ts
our pool got way too big to be safely converted to number
=> fix: big number error

apps/web/src/App.tsx
=> fix: cannot read properties of undefined (reading 'foreground') #499

apps/web/public/locales/en/translation.json, apps/web/src/archetypes/Crowdloan/Indexx.tsx, apps/web/src/components/NoResults.js, apps/web/src/libs/talisman/util/_config.ts
- Fix copy for no crowdloans
- Add Hashed crowdloan
- Add Shiden crowdloan
=> chore: add crowdloans, fix copy

apps/web/src/libs/talisman/util/_config.ts
Add Invarch crowdloan.
Closes #541
=> feat: add invarch CL

apps/web/src/components/widgets/AccountsManagementMenu.tsx, packages/ui/src/atoms/Dialog.tsx
check for clicked element instead of stopping event propagation
=> refactor: dialog backdrop click capture

README.md
fix: script name in package.json should be dev not start
=> fix: update readme to use valid script name

apps/web/src/components/widgets/AddReadOnlyAccountDialog.tsx, apps/web/src/util/addressValidation.ts
same public key with different ss58 prefix
=> fix: watch only account duplicates

README.md
See: https://github.com/TalismanSociety/talisman-web/pull/544#issuecomment-1468973743 & https://github.com/TalismanSociety/talisman-web/issues/546
=> Remove broken link to the security audit

apps/web/src/archetypes/NFT/List.tsx, apps/web/src/libs/@talisman-nft/providers/Acala/AcalaProvider.ts, apps/web/src/libs/@talisman-nft/providers/RMRK1/Rmrk1Provider.ts, apps/web/src/libs/@talisman-nft/providers/RMRK2/Rmrk2Provider.ts, apps/web/src/libs/@talisman-nft/providers/Statemine/StatemineProvider.ts
=> fix: stopgap fix for nfts performance

apps/web/src/components/recipes/AddStakeDialog/AddStakeDialog.tsx, apps/web/src/components/recipes/StakingInput/StakingInput.tsx, apps/web/src/components/recipes/UnstakeDialog/UnstakeDialog.tsx, packages/ui/src/global.d.ts, packages/ui/src/molecules/TextInput/TextInput.stories.tsx, packages/ui/src/molecules/TextInput/TextInput.tsx
allow error label at any position rather than being fixed
=> refactor: input error label

apps/web/src/components/recipes/StakeForm/StakeForm.stories.tsx, apps/web/src/components/recipes/StakeForm/StakeForm.tsx, apps/web/src/components/widgets/staking/StakeForm.tsx
- update copy for non DOT pools
=> fix: copy for non-polkadot pools

packages/ui/src/atoms/Button/Button.stories.tsx, packages/ui/src/atoms/Button/Button.tsx
- better alignment
- add more button stories
=> style: button

apps/web/src/components/recipes/AddReadOnlyAccountDialog/AddReadOnlyAccountDialog.tsx, apps/web/src/components/recipes/AddStakeDialog/AddStakeDialog.tsx, apps/web/src/components/recipes/StakeForm/StakeForm.tsx, apps/web/src/components/recipes/TeleportForm/TeleportForm.tsx, apps/web/src/components/recipes/TokenSelectorDialog/TokenSelectorDialog.tsx, apps/web/src/components/recipes/UnstakeDialog/UnstakeDialog.tsx, packages/ui/src/molecules/TextInput/TextInput.tsx
change from 30px to a reasonable default of 14px
=> refactor: change `TextInput` default font size

apps/web/src/routes/index.tsx
this doesn't add value anymore since we moved to multichain support
=> perf: remove pre-loading

apps/web/src/domains/nfts/recoils.ts, packages/utils/src/react/usePagination.ts
incorrect `hasNext` calculation
=> fix: nfts pagination & parsing

apps/web/package.json, yarn.lock
Includes XCM v3 support on Acala
https://github.com/polkawallet-io/bridge/commit/639f9d58151e1c2cb105d501a37de09872e53366
=> chore: bump polkawallet bridge

packages/ui/src/atoms/Button/Button.tsx, packages/ui/src/atoms/Chip/Chip.tsx, packages/ui/src/atoms/Text/Text.tsx, packages/ui/src/molecules/ContainedTextInput/ContainedTextInput.tsx, packages/ui/src/molecules/SegmentedButton/SegmentedButton.tsx, packages/ui/src/molecules/Tabs/Tabs.tsx, packages/ui/src/molecules/TextInput/TextInput.tsx
Use color from CSS rather than JS props
=> refactor: text component color

apps/web/src/App.tsx, apps/web/src/domains/extension/TalismanExtensionSynchronizer.tsx, apps/web/src/domains/extension/index.ts
=> feat: sync custom assets, chains & networks with Talisman extension

apps/web/package.json, apps/web/src/components/widgets/dex/TransportForm.tsx, apps/web/src/domains/bridge/config.ts, yarn.lock
- New routes to & from HydraDX
- Additional networks: Centrifuge, Robonomics, Tinkernet, Zeitgeist
=> build: bump polkawallet bridge

apps/web/src/archetypes/Crowdloan/Contribute.tsx, apps/web/src/components/widgets/AccountsManagementMenu.tsx, apps/web/src/components/widgets/dex/SwapForm.tsx, apps/web/src/components/widgets/dex/TransportForm.tsx, apps/web/src/components/widgets/staking/StakeForm.tsx, apps/web/src/domains/accounts/recoils.ts, apps/web/src/domains/balances/recoils.ts, apps/web/src/domains/extension/recoils.ts, apps/web/src/domains/fastUnstake/hooks.ts, packages/ui/src/atoms/Tooltip/Tooltip.tsx
=> feat: sync watched-only accounts between extension and portal

apps/web/package.json, apps/web/src/domains/balances/currency.ts, packages/ui/src/atoms/AnimatedNumber/AnimatedNumber.tsx, yarn.lock
- stronger type checking
- fix intermittent bug where animated number might reset to 0 when currency change
=> refactor: multi-currency improvements

apps/multisig/src/components/AmountFlexibleInput/index.tsx, apps/multisig/src/components/AmountRow.tsx, apps/multisig/src/domains/chains/extrinsics.ts, apps/multisig/src/domains/chains/supported-chains.ts, apps/multisig/src/domains/chains/tokens.ts, apps/multisig/src/domains/multisig/index.ts, apps/multisig/src/domains/referenda/index.ts, apps/multisig/src/layouts/Overview/NewTransactionModal/ActionsMenu.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/index.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/ConvictionsDropdown.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/ProposalsDropdown.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/VoteOptions.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/VotingForm.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/index.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/mode/VoteStandard.tsx, apps/multisig/src/layouts/Overview/Transactions/FullScreenSummary.tsx, apps/multisig/src/layouts/Overview/Transactions/TransactionDetailsExpandable.tsx, apps/multisig/src/layouts/Overview/Transactions/TransactionSummaryRow.tsx, apps/multisig/src/layouts/Overview/Transactions/TransactionSummarySideSheet.tsx, apps/multisig/src/layouts/Overview/Transactions/VoteTransactionDetails.tsx, apps/multisig/src/util/numbers.ts
This PR creates a UI for users to easily vote on a proposal as a Multisig.
Create and Approve a Vote tx:
https://github.com/TalismanSociety/talisman-web/assets/81092286/d5636b23-18d3-4d3e-bd7c-9e229022c4ea
View, Approve and Execute a Vote tx:
https://github.com/TalismanSociety/talisman-web/assets/81092286/dbe793f4-ada9-4b69-891a-bb98dccb3141
=> feat(signet): form to select a proposal and enter vote parameters

apps/web/src/components/widgets/staking/Stakes.tsx, apps/web/src/domains/staking/hooks/useTotalStaked.ts
=> feat: cross chain stake total

apps/multisig/src/layouts/Overview/Transactions/FullScreenSummary.tsx, apps/multisig/src/layouts/Overview/Transactions/index.tsx
This PR removes the confusing Pending status pill when creating a tx
=> fix: hide tx status pill when creating tx

apps/multisig/src/components/AddressInput/AccountDetails.tsx, apps/multisig/src/components/AddressInput/NameAndAddress.tsx, apps/multisig/src/components/AddressInput/SelectedAddressPill.tsx, apps/multisig/src/components/AddressInput/index.tsx, apps/multisig/src/components/ChainPill.tsx, apps/multisig/src/domains/common/substratePolyfills.ts, apps/multisig/src/domains/proxy/useProxies.ts, apps/multisig/src/layouts/Overview/Assets.tsx, apps/multisig/src/layouts/Overview/VaultOverview.tsx, apps/multisig/src/layouts/Overview/index.tsx
This PR implements the new vault overview UI in the dashboard
https://github.com/TalismanSociety/talisman-web/assets/81092286/0e25b694-c24a-4805-b714-ec7f2eb8b110
=> feat: signet new dashboard vault view

apps/multisig/src/components/AddressInput/index.tsx, apps/multisig/src/components/Alert.tsx, apps/multisig/src/components/MultisigSelect.tsx, apps/multisig/src/domains/multisig/index.ts, apps/multisig/src/domains/proxy/useProxies.ts, apps/multisig/src/domains/proxy/util.ts, apps/multisig/src/layouts/AddVault/CreateVault/index.tsx, apps/multisig/src/layouts/AddVault/ImportVault/ProxiedAccountSettings.tsx, apps/multisig/src/layouts/AddVault/ImportVault/index.tsx, apps/multisig/src/layouts/AddVault/common/Confirmation.tsx, apps/multisig/src/layouts/AddVault/common/useAugmentedAccounts.ts, apps/multisig/src/layouts/AddVault/index.tsx, apps/multisig/src/layouts/Header.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/SendAction.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/multisend/MultiSendForm.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/multisend/index.tsx, apps/multisig/src/layouts/Overview/NewTransactionModal/vote/VotingForm.tsx
This PR allows importing any vaults into Signet, including non-Any type proxies.
- UI for importing vault
- Prevent duplicate vault setup
- proxy type gated actions
=> feat: signet import vaults

.github/workflows/deploy.yml
https://github.com/cloudflare/pages-action/issues/97
=> ci: add branch name to Cloudflare pages action

apps/web/src/components/widgets/history/History.tsx, apps/web/src/routes/portfolio/overview.tsx
Always defaulting to current selected accounts make search by hash impossible
=> fix: history search by hash

apps/web/src/domains/staking/substrate/useTotalStaked.ts
- Remove testnet from calculation
- Only include active amount in total
=> fix: staking total

apps/web/src/domains/staking/substrate/useTotalStaked.ts
use `derive.staking.accounts` instead of `query.staking.ledger.multi`
=> fix: total stake amount

apps/web/src/domains/nfts/core.ts, apps/web/src/routes/portfolio/collectibles.tsx, packages/ui/src/atoms/CircularProgressIndicator/CircularProgressIndicator.tsx
Shows a small status indicator next to account name to indicate whether all NFTs have been loaded.
=> feat: nfts loading status indicator

apps/web/src/routes/portfolio/collectibles.tsx, packages/nft/src/generators/rmrk2.ts
- [fix: rmrk2 NFT link to Singular](https://github.com/TalismanSociety/talisman-web/commit/94f27e1e307ef0db492d3cb73e8ec8248e2f0dda)
- [feat: add RMRK2 NFT link to Kodadot](https://github.com/TalismanSociety/talisman-web/commit/9dd868ec557de20bede2012bc02192fdbfa66adf)
=> chore: fix & update RMRK2 external link

apps/web/src/domains/staking/substrate/nominationPools/hooks/usePoolStake.ts
=> fix: recoils transition bug

apps/web/src/archetypes/Wallet/Crowdloans.tsx, apps/web/src/domains/accounts/recoils.ts
This behaviour is inconsistent with the rest of portfolio overview
=> fix: non-selected readonly account shows up in crowdloans overview

apps/web/src/components/widgets/PortfolioAllocationGraph.tsx
this will match what we display on the extension
=> feat: better portfolio state breakdown

apps/web/src/domains/bridge/extendedRoutes.ts
Declaring new properties will overwrite existing ones from super class
=> fix: extended XCM adapters

apps/web/src/components/widgets/staking/dappStaking/StakeProviders.tsx
DApp staking staked balance is part of free balance
=> fix: dapp staking stake percentage

apps/web/src/components/recipes/StakeProvider/StakeProvider.tsx, apps/web/src/components/widgets/staking/dappStaking/StakeProviders.tsx, apps/web/src/components/widgets/staking/lido/StakeProviders.tsx, apps/web/src/components/widgets/staking/slpx/StakeProviders.tsx, apps/web/src/components/widgets/staking/substrate/StakeProviders.tsx
Move suspense fallback logic into `StakeProvider` component
=> refactor: stake provider suspense

apps/web/src/domains/staking/dappStaking/hooks/useApr.ts
Can happen for a very short window in the beginning of the voting period
=> fix: check for DAppStaking Infinity APR

apps/web/src/components/recipes/DappStakingForm/DappStakingForm.tsx
- Remove weekly claim suggestion (this make no sense)
- Add "Learn more" link
=> chore: update DApp staking small text

apps/web/.storybook/preview.tsx, apps/web/src/App.Theme.tsx, apps/web/src/theme.d.ts, packages/ui/.storybook/preview.tsx, packages/ui/README.md, packages/ui/assets/css/talismn.css, packages/ui/src/atoms/Chip/Chip.stories.tsx, packages/ui/src/theme.stories.tsx, packages/ui/src/theme.tsx
- Remove required reference to `@emotion/react`
- Dynamically style root font style & background base on theme
=> refactor: misc theme improvements

apps/web/src/components/recipes/AddStakeDialog/AddStakeDialog.tsx, apps/web/src/components/recipes/ClaimStakeDialog/ClaimStakeDialog.tsx, apps/web/src/components/recipes/DappStakingLockedAmountDialog/DappStakingLockedAmountDialog.tsx, apps/web/src/components/recipes/ExportHistoryAlertDialog/ExportHistoryAlertDialog.tsx, apps/web/src/components/recipes/FastUnstakeDialog/FastUnstakeDialog.tsx, apps/web/src/components/recipes/PoolClaimPermissionForm/PoolClaimPermissionForm.tsx, apps/web/src/components/recipes/StakeCalculatorDialog/StakeCalculatorDialog.tsx, apps/web/src/components/recipes/StakeProvidersDialog/StakeProviderDialog.tsx, apps/web/src/components/recipes/StakeTargetSelectorDialog/StakeTargetSelectorDialog.tsx, apps/web/src/components/recipes/TokenSelectorDialog/TokenSelectorDialog.tsx, apps/web/src/components/recipes/UnstakeAlertDialog/UnstakeAlertDialog.tsx, apps/web/src/components/recipes/UnstakeDialog/UnstakeDialog.tsx, apps/web/src/components/widgets/staking/dappStaking/DappPickerDialog.tsx, packages/ui/src/molecules/AlertDialog/AlertDialog.tsx
As this value is optionally applied depending on the view port size
=> refactor: rename `width` to `targetWidth`

apps/web/src/components/recipes/DexForm/TransportForm/TransportForm.tsx
https://github.com/framer/motion/issues/2563
=> fix: transport form inverse route button animation

apps/portal/src/libs/talisman/crowdloan.tsx, apps/portal/src/libs/talisman/parachain.tsx
TODO: need to remove these context providers entirely & replace with recoils or jotai
=> perf: remove suspense from provider

apps/portal/src/domains/staking/dappStaking/hooks/useStake.ts
=> fix: dapp staking staker rewards calculation

apps/portal/src/components/recipes/DexForm/TransportForm/TransportForm.tsx, apps/portal/src/components/recipes/ExportTxHistoryDialog/ExportTxHistoryDialog.tsx, apps/portal/src/components/widgets/AccountSelector.tsx, apps/portal/src/components/widgets/staking/dappStaking/StakeSideSheet.tsx, apps/portal/src/components/widgets/staking/substrate/StakeForm.tsx, apps/portal/src/routes/layout.tsx, apps/portal/src/routes/portfolio/collectibles.tsx, packages/ui/src/molecules/Select/Select.stories.tsx, packages/ui/src/molecules/Select/Select.tsx
To avoid possible clash with native html select element `onChange`
=> refactor: rename `Select.onChange` to `Select.onChangeValue`

packages/ui/src/molecules/Select/Select.tsx
Dynamic border radius sometimes yield incorrect value
=> fix: select component animation

apps/portal/src/components/widgets/staking/lido/LidoWidgetSideSheet.tsx
This reverts commit 21a1846fedb2e4bc9621f5546edcff7654778260.
=> chore: re-enable Lido staking widget

packages/ui/src/atoms/Button/Button.tsx
- Adjust paddings
- Have leading & trailing icon anchored to the text rather than the outer edge
=> style: update button component

apps/portal/src/components/legacy/archetypes/Portfolio/Assets.tsx, apps/portal/src/routes/portfolio/overview.tsx
- Wrap all calculation in `useMemo`
- Use 1 hook instead of 2 hooks with mostly duplicated logic
=> perf: improve assets overview

apps/portal/src/components/recipes/DappStakingForm/DappStakingForm.tsx, apps/portal/src/components/widgets/staking/dappStaking/StakeSideSheet.tsx
- Highlight current staked balance
- Include current staked balance to the estimated return calculation
=> feat: improve display of DApp staking existing amount

apps/portal/src/domains/staking/dappStaking/hooks/useStakeLoadable.ts
Updated logic to take into account locked tokens when displaying positions row for Astar. This will give the users the opportunity to re-stake or un-stake their tokens instead of not displaying their position at all.
Tokens remain locked but not staked on a couple of cases: 
- "... During the migration to dApp Staking v3...".
- "... at the beginning of each period all tokens will be unstaked, but they will remain locked.".
For more on this read their [blogpost](https://astar.network/blog/dapp-staking-v3-explained-48693).
Please delete options that are not relevant.
=> [FIX] - Display Astar position if tokens are locked but not staked

apps/portal/src/domains/staking/slpx/config.ts
Updated Bifrost api.
- Before
- After
=> fix: update Bifrost api

apps/portal/src/domains/staking/subtensor/hooks/forms.ts
When staking with bittensor, add a remark on chain
=> feat: bittensor stake with remark

apps/portal/src/domains/nfts/worker.ts, packages/nft/src/generators/unique.ts
Fixes:
- EVM accounts not fetching unique NFTs
- Unique NFT images not showing due to change in the API response
=> fix: unique nfts

README.md
=> fix(readme.md): broken blog link

apps/portal/src/domains/staking/subtensor/hooks/useApr.ts, apps/portal/vite.config.ts
Added average TAO api placeholder fallback.
=> chore: TAO apy placeholder

apps/portal/src/domains/staking/subtensor/hooks/forms.ts
Fixes "Max" TAO staking fee estimation.
A dummy `feeEstimateTx` was being used for estimation the transaction fee, when actually `tx` was being submitted. The fix is using the real `tx` that is submitted to calculate the fees.
Note: After submitting the staked % will show 94%, this is due to the fact that other connected wallets also hold TAO in them. It has in fact staked 100% of the walled used for this transaction, I would have to wait another 360 blocks to record another demo.
https://github.com/user-attachments/assets/634f33eb-534f-4771-a06e-98cca7873b0e
=> fix: tao staking fee estimation

apps/portal/src/domains/common/recoils/api.ts, apps/portal/src/routes/layout.tsx, apps/portal/src/routes/transport/index.tsx
Fixes infinite rerender caused by jotai
=> fix: swap page infinite rerender

apps/portal/src/routes/portfolio/collectibles.tsx
NFT dialog not displaying "OG WUD BURN" collection.
https://github.com/user-attachments/assets/2c217e3c-4edf-4213-ac71-f7de4f9c98f9
=> fix: NFT dialog not displaying OG WUD BURN collection

apps/portal/src/components/recipes/StakePosition/StakePosition.tsx, yarn.lock
Minor fixes:
- use now.sh instead of vercel.app for azero resolver package. Was getting checksum unmet issue when pointing to vercel.app
- add key to mapped items in StakePosition.tsx
=> fix: use now.sh and add key to mapped items

apps/portal/src/components/recipes/StakePosition/StakePosition.tsx, apps/portal/src/components/widgets/staking/substrate/PoolStakeItem.tsx, apps/portal/src/domains/chains/config.ts, apps/portal/src/domains/common/hooks/useLocalizedFiatAmount.ts, apps/portal/src/domains/staking/substrate/nominationPools/hooks/useTotalRewards.ts
- Ensure proper error management when network problems prevent fetching staking rewards 
- Allow staking components to accept undefined rewards values
- Update Nova wallet subquery indexer URL for staking rewards
=> Staking rewards network request issues

apps/portal/.env.example, apps/portal/src/domains/staking/slpx/config.ts, apps/portal/src/domains/staking/slpx/constants.ts, apps/portal/src/domains/staking/slpx/core.ts, apps/portal/src/domains/staking/slpx/mantaPacificSlpxAbi.ts, apps/portal/src/vite-env.d.ts
- Updated `mantaPacificSlpxAbi`
- Updated manta mint and redeem functions
- added `VITE_TALISMAN_BIFROST_CHANNEL_ID` env var to channel_id to identify txs from Talisman
=> feat: vMANTA abi update, added Talisman channel_id

apps/portal/src/domains/staking/substrate/validator/hooks/useTotalRewards.ts
Add try catch block to handle  ValidatorStakes useTotalRewrads errors without crashing.
=> fix: catch errors in useTotalRewards

apps/portal/src/components/widgets/staking/slpxSubstrate/UnstakeDialog.tsx
Default unlock duration to 0 when formatting time distance.
=> fix: vDOT unbonding period 

apps/portal/src/domains/staking/subtensor/atoms/delegates.ts
Updated TAO default delegator to Taofu
=> chore: updated featured/default tao delegator

apps/portal/.env.example, apps/portal/src/components/widgets/SiteNav.tsx, apps/portal/src/vite-env.d.ts
Navigate to Ramp when clicking on Buy/Sell
https://github.com/user-attachments/assets/ccf5dd4a-cc22-4f7c-8351-09f88277b419
=> feat: add ramp, remove banxa

apps/portal/src/domains/chains/config.ts, apps/portal/src/domains/staking/substrate/nominationPools/hooks/useTotalRewards.ts
Some of the indexer URLs were out of date!
=> fix: total staking rewards

apps/portal/package.json, apps/portal/src/App.tsx, apps/portal/src/components/molecules/CurrencySelect.tsx, apps/portal/src/components/widgets/xcm/api/atoms/configServiceAtom.ts, apps/portal/src/components/widgets/xcm/api/atoms/pjsApiAtom.ts, apps/portal/src/components/widgets/xcm/api/utils/wrapChainApi.ts, apps/portal/src/domains/common/atoms/apiPromiseAtom.ts, apps/portal/src/domains/common/recoils/api.ts, apps/portal/src/util/jotaiStore.tsx, yarn.lock
This PR implements a fix to route all xcm websocket requests via Talisman Wallet, leading to improved reliability and performance.
Note: depends on https://github.com/TalismanSociety/talisman-web/pull/1234 to be merged first
=> fix: shared xcm sdk websockets

apps/portal/src/components/recipes/Asset.tsx, apps/portal/src/components/recipes/AssetNetworksLogoStack.tsx
=> fix: prevent AssetNetworksLogoStack from breaking the UI layout

apps/portal/src/components/molecules/WalletConnectionButton.tsx, apps/portal/src/components/widgets/swap/SwapTokensModal.tsx, apps/portal/src/components/widgets/swap/swap-balances.api.ts, apps/portal/src/components/widgets/swap/swap-modules/chainflip.swap-module.ts, apps/portal/src/components/widgets/swap/swap-modules/common.swap-module.ts, apps/portal/src/components/widgets/swap/swap-modules/lifi.swap-module.ts, apps/portal/src/components/widgets/swap/swaps.api.ts
Some small fixes I ran into while porting swaps to the wallet
- fix: ui bug when more than 9 accounts connected
- fix: `TS Expression produces a union type that is too complex to represent` error
=> fix: small fixes

apps/portal/package.json, apps/portal/src/components/widgets/swap/curated-tokens.tsx, apps/portal/src/components/widgets/swap/swap-modules/common.swap-module.ts, apps/portal/src/components/widgets/swap/swap-modules/simpleswap-swap-module.ts, packages/nft/package.json, yarn.lock
Adds `s` token on `s` chain (sonic) to swaps, via simpleswap.
=> feat: add s to swaps

apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx, apps/portal/src/components/widgets/staking/subtensor/StakeForm.tsx, apps/portal/src/domains/staking/subtensor/atoms/taostats.ts, apps/portal/src/domains/staking/subtensor/hooks/useApr.ts
Add default values when Taostats api calls fails.
=> fix: add default values when api fails

apps/portal/src/domains/staking/utils/getPosition.ts
- Reposition Analog chain
- Create position map to handle re-ordering easier
=> refactor: position map, reposition analog chain

apps/portal/src/components/widgets/staking/subtensor/SubtensorStakingForm.tsx, apps/portal/src/domains/staking/subtensor/atoms/debug.ts, apps/portal/src/domains/staking/subtensor/hooks/forms.ts
Removed rootnet staking fees
https://github.com/user-attachments/assets/c5dd31d9-3b3c-4cdc-9bfc-27d3d3caef67
=> chore: removed Tao rootnet staking fees

apps/portal/src/components/widgets/staking/subtensor/DelegateSelectorDialog.tsx
Changes the default Validator modal filter to "Total staked"
https://github.com/user-attachments/assets/07e218a3-828d-4130-a358-1fe2864e5c01
=> chore: chage validator selec modal default filter to Total staked

apps/portal/src/domains/staking/subtensor/hooks/useGetBittensorSupportedDelegates.ts
Updated Yuma's delegator fallback hotkey.
=> chore: updated Yuma hotkey

apps/portal/package.json, apps/portal/src/components/recipes/StakePosition.tsx, apps/portal/tailwind.config.js, yarn.lock
<div align="center">
**before**
**after**
</div>
=> fix: rejig staked balance and asset onto one row in StakePosition

apps/portal/codegen.nova.ts, apps/portal/src/domains/staking/substrate/nominationPools/hooks/useTotalRewards.ts, apps/portal/src/generated/gql/nova/gql/gql.ts, apps/portal/src/generated/gql/nova/gql/graphql.ts
<div align="center">
**before**
**after**
</div>
=> feat: show analog total nompool rewards

apps/portal/src/components/widgets/swap/side-panel/SwapDetails.tsx, apps/portal/src/components/widgets/swap/swap-modules/simpleswap-swap-module.ts
When no routes are found, this PR will fetch & show the minimum amount of tokens needed to perform a swap via SimpleSwap.
=> feat: show simpleswap minimum swap amount

apps/portal/src/components/widgets/swap/swap-modules/chainflip.swap-module.ts, apps/portal/src/components/widgets/swap/swap-modules/common.swap-module.ts, apps/portal/src/components/widgets/swap/swap-modules/simpleswap-swap-module.ts, apps/portal/src/hooks/useSubstrateBalance.ts, apps/portal/src/hooks/useSubstrateToken.ts
Adds back swaps routes for USDC/USDT on assethub. We need to wait for simpleswap's api to come back before we can test this.
=> fix: assethub assets swaps

apps/portal/src/components/widgets/staking/providers/hooks/subtensor/useSubtensorProviders.ts
[on sentry](https://talisman.sentry.io/issues/6288867228/events/8b752997c083474bbabe951d1566e0b1?project=4504672439697408)
=> fix: staking crash

apps/portal/package.json, yarn.lock
- Bump vite to a secure version, issue https://github.com/advisories/GHSA-g4jq-h2w9-997c
=> chore: bump vite version
